# Generated by Django 6.0.4 on 2026-04-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom', models.CharField(max_length=100)),
                ('bride', models.CharField(max_length=100)),
                ('wedding_date', models.DateTimeField()),
                ('venue_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=50)),
                ('card_owner', models.CharField(max_length=100)),
                ('music', models.FileField(blank=True, null=True, upload_to='wedding_music/')),
                ('slug', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
    ]
